### ISSUE TITLE
Badge is reporting 'not found' when actually passing

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#223]
![image](https://user-images.githubusercontent.com/1980785/55110023-5f8d7a00-5094-11e9-849c-c236f28a28eb.png)   
... as seen in:
https://github.com/brianegan/flutter_architecture_samples
This is the currently passing build:
https://cirrus-ci.com/build/6482870825648128
May have something to do with being a first build,... or manual reruns on a task, for example:
https://cirrus-ci.com/task/5753077868003328

**Comment by fkorotkov** [comment]
Weird since the link points to the right badge: https://api.cirrus-ci.com/github/brianegan/flutter_architecture_samples.svg

**Comment by RDIL** [comment]
I see a green badge in your comment...

**Comment by fkorotkov** [comment]
Could it be that GitHub cached the redirect when it was failing?

**Comment by fkorotkov** [comment]
Some mystery of GitHub rendering... Let me poke around... 🤔

**Comment by fkorotkov** [comment]
Seems GH pre-renders Markdown and caches it. Not sure how to avoid it.

<img width="910" alt="Screen Shot 2019-03-27 at 4 45 17 PM" src="https://user-images.githubusercontent.com/989066/55111000-beacb800-50af-11e9-9cf6-41b0b76e6b61.png">

**Comment by mmcc007** [comment]
Right, I'm seeing
![image](https://user-images.githubusercontent.com/1980785/55111789-63bb9680-5098-11e9-987b-7c30a0716798.png)
now.
Maybe it rebuilds cache periodically. (I was doing a bunch of rebuilds due to transient flutter timeouts about an hour or so ago). Will report back if I see a change.

**Comment by mmcc007** [comment]
BTW: I am currently seeing:
![image](https://user-images.githubusercontent.com/1980785/55113012-3ae8d080-509b-11e9-8ded-e0c3bfb183e4.png)
in
https://github.com/niieani/bash-oo-framework
which is a first build as of about 20 minutes ago:
https://github.com/niieani/bash-oo-framework/pull/83

**Comment by fkorotkov** [comment]
@mmcc007 I've switched away from redirecting to cacheble shields to proxying them with `no-cache`. Should fix the issue but will need to wait for GitHub to invalidate the cache.

**Comment by mmcc007** [comment]
FYI: 
https://github.com/brianegan/flutter_architecture_samples
is showing the passing badge correctly.

https://github.com/niieani/bash-oo-framework
is still showing the 'not found' badge when actually passing

**Comment by fkorotkov** [comment]
Seems `bash-oo-framework` still cached:

![image](https://user-images.githubusercontent.com/989066/55187789-4659fb80-5170-11e9-8a36-390c21322991.png)

**Comment by mmcc007** [comment]
brianegan/flutter_architecture_samples also seems to be still cached (if I'm reading this correctly)

![Screen Shot 2019-03-28 at 1 20 45 PM](https://user-images.githubusercontent.com/1980785/55190072-6bdd0a00-515c-11e9-957e-83f42c4d639b.png)
But anyway, it's bound to invalidate cache at some point... so I'm not going to worry about it 😀

**Comment by claudioandre-br** [comment]
This is happening with me for 5 (five) weeks.

`https://api.cirrus-ci.com/github/<USER OR ORGANIZATION>/<REPOSITORY>.svg`

- https://cirrus-ci.com/github/claudioandre-br/JohnTheRipper (works)
- https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg (ci not found)
[![Build Status](https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg)](https://cirrus-ci.com/github/claudioandre-br/JohnTheRipper)

**Comment by fkorotkov** [comment]
@claudioandre-br it seems your default branch is not `test` so you need explicitly specify it in the URL:

https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg?branch=test

**Comment by mmcc007** [comment]
Should probably consider using a different image for branches with no builds yet. The image might be a bit non-intuitive for some (like first time users).
For example, travis shows:
![Screen Shot 2019-06-08 at 8 48 14 AM](https://user-images.githubusercontent.com/1980785/59149465-352c3700-89ca-11e9-8868-f8dcbfdb5879.png)
and suggests creating a build.
https://cirrus-ci.com/github/mmcc007/default_flutter_app

Cirrus provides no similar suggestions (other than a plus sign):
https://travis-ci.com/mmcc007/default_flutter_app
which may be a little non-intuitive for first time users.

**Comment by fkorotkov** [comment]
Another option is to use overall the latest build if there is none for the default branch 🤔

**Comment by claudioandre-br** [comment]
> Or once there will be a build for the default bleeding-jumbo branch, then the badge will work. ok

> Another option is to use overall the latest build if there is none for the default branch thinking

There is no  "default branch thinking" or I'm still doing something wrong. The default-branch is `bleeding-jumbo` not `master`. So:

![Build Status](https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg) (no branch info)
![Build Status](https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg?branch=master) (using `?branch=master`)
![Build Status](https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg?branch=bleeding-jumbo) (using `?branch=bleeding-jumbo`)
![Build Status](https://api.cirrus-ci.com/github/claudioandre-br/JohnTheRipper.svg?branch=test) (using `?branch=test`)

**Comment by fkorotkov** [comment]
@claudioandre-br It was still defaulting to `master` for your repo. Should be working now. Sorry for the inconvenience!
