### ISSUE TITLE
Artifact download links for Windows containers return 404

### ISSUE THREAD

**Issue by morganwillcock** [cirruslabs/cirrus-ci-docs#346]
# Expected Behavior

Windows container uploads an artifact, the web UI gives a working download link for the artifact.

# Real Behavior

Windows container uploads an artifact, but the web UI provides a link that returns a 404 error.
An example task is here: https://cirrus-ci.com/task/6282548374667264

<pre>Uploading 1 artifacts for C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build\VS2015\lib\alleg-*.lib
Uploaded C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build\VS2015\lib\alleg-static.lib</pre>

Artifact URL from the WebUI returns 404:

```
curl https://api.cirrus-ci.com/v1/artifact/task/6282548374667264/binary/build/VS2015/lib/alleg-static.lib
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /v1/artifact/task/6282548374667264/binary/build/VS2015/lib/alleg-static.lib. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```

I've tried specifying slashes in the opposite direction:

<pre>  binary_artifacts:
    path: build\VS2015\lib\alleg-*.lib</pre>

<pre>  binary_artifacts:
    path: build/VS2015/lib/alleg-*.lib</pre>

...but this doesn't seem to make a difference.

I'm also unable to find a working URL for the latest artifact:
https://api.cirrus-ci.com/v1/artifact/github/morganwillcock/lib-allegro/build_windows/binary/build/VS2015/lib/alleg-static.lib

I'm guessing that something isn't working for artifact uploads from Windows containers, or there is something about the path that is causing a problem? Linux containers seemed fine, although the artifact path I'm using on Linux doen't involve sub-directories.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: (~~DockerLinux~~, ~~macOS~~, Windows, ~~FreeBSD~~)
  - Task name: build_windows
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
A fix was just merged and will be included in the next Cirrus CI deployment today. Will close the issue once it will be available. Sorry for the inconvenience!

**Comment by fkorotkov** [comment]
Forgot to close the issue. This is fixed now and new tasks will have proper links.

**Comment by morganwillcock** [comment]
@fkorotkov Thanks. It seems that trying to download the latest version using the API link still doesn't find a valid file. I restarted the build so here is a newer run of the task:
https://cirrus-ci.com/task/5756246806757376

Web UI download is now working:
https://api.cirrus-ci.com/v1/artifact/task/5756246806757376/binaries/build/VS2015/lib/alleg-static.lib

Trying to download the most recent artifact returns a 404 message for both methods:
https://api.cirrus-ci.com/v1/artifact/github/morganwillcock/lib-allegro/build_windows/binaries/build/VS2015/lib/alleg-static.lib
https://api.cirrus-ci.com/v1/artifact/github/morganwillcock/lib-allegro/build_windows/binaries.zip

This based on the documentation saying:
```
https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>/<PATH>
https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>.zip
```

Am I doing something wrong here or is there still a problem?

**Comment by fkorotkov** [comment]
Since it's not a default branch you need to add `?branch=cirrus-ci`:

https://api.cirrus-ci.com/v1/artifact/github/morganwillcock/lib-allegro/build_windows/binaries.zip?branch=cirrus-ci
