### ISSUE TITLE
[Prio High] Merging YAML maps via anchors are applied in incorrect order

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#413]
When using YAML Anchors and merging a YAML map into another map, the merge happens in the incorrect order.

Consider this example:

```yaml
otherEnv: &otherEnv
  foo: baz

task:
  env:
    <<: *otherEnv
    foo: bar
  script: echo $foo
```

This prints: `baz`.

What I would expect: `bar`.

I.e. In the `env` section where I merge the yaml maps, the last occurrence of a key should always win. This is the spec compliant behavior in JavaScript and JSON parsers and a quick check on [https://yaml-online-parser.appspot.com/](https://yaml-online-parser.appspot.com/?yaml=otherEnv%3A+%26otherEnv%0A++foo%3A+baz%0A%0Atask%3A%0A++env%3A%0A++++%3C%3C%3A+*otherEnv%0A++++foo%3A+bar%0A++script%3A+echo+%24foo&type=json) (which is supposedly yaml 1.2) yields the same result.

In cirrus ci the merging behaviour is exactly the other way around.
If I change
```yaml
  env:
    <<: *otherEnv
    foo: bar
```
to
```yaml
  env:
    foo: bar
    <<: *otherEnv
```
I sort of get the "expected" output (`bar`) which very surprising.

Since this behaviour can lead to very weird, hard to debug and accidental surprises (i.e. deploying to the wrong environment or applying incorrect configs) I consider this a high priority to get fixed.

Thanks :)

**Comment by fkorotkov** [comment]
Seems working for me: https://cirrus-ci.com/task/5352242801016832?command=main#L1

**Comment by geekflyer** [comment]
is this after a fix? 😀

**Comment by fkorotkov** [comment]
Have't touched it. Wrote a test that worked, got surprised and verified. Is it the exact config that you've tried? Maybe there are some other complications?

**Comment by geekflyer** [comment]
Ok, indeed the very simple example from above works. Found out the issue occurs only in conjunction with setting (anything) in the global `env` section.

So this example demonstrates the bug:

```
env:
  somethingelse: haha  

otherEnv: &otherEnv
  foo: baz

task:
  env:
    <<: *otherEnv
    foo: bar
  script: echo $foo
```

will print $baz

**Comment by fkorotkov** [comment]
Yes! That's reproduces in tests. 🙌

**Comment by fkorotkov** [comment]
Should be fixed now

**Comment by geekflyer** [comment]
@fkorotkov Unfortunately this still appears to be still not fully fixed. When it comes to merging stuff into `env` it works, but I have another case where I'm merging things into `gke_container` which misbehaves.
See the example below:

```yaml
.common:
  buildContainer: &buildContainer
    cluster_name: clusterB

gke_container:
  cluster_name: clusterA
  image: ubuntu

# cirrus ci will attempt to run this task in clusterB instead of clusterC
some_task:
  <<: *buildContainer
  cluster_name: clusterC

```

**Comment by fkorotkov** [comment]
Can reproduce in tests. Will fix it. 👌

**Comment by fkorotkov** [comment]
This is fixed as well now. 🙌
