### ISSUE TITLE
Rust's cargo cache doesn't work with FreeBSD instances

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#463]
Rust's cargo cache, unsurprisingly, does not work with FreeBSD instances.  It seems to only work with the Rust Docker images.  Enabling it for FreeBSD instances would save developers time and save Cirrus $$$ (for open-source projects, at least).  What would be required?  I'm willing to help, if possible.

Here's an example of a 23m build that probably take < 2m if the cargo cache worked.
https://cirrus-ci.com/task/6286131638829056

**Comment by fkorotkov** [comment]
It seems that `$CARGO_HOME/registry` is resolved to just `/registry` which is empty and that's why registry is not caching. Seem you might want to specify the path to registry explicitly.

**Comment by asomers** [comment]
So that problem was easy.  `$CARGO_HOME` isn't defined by default; one should use `$HOME/.cargo` instead.  But it still isn't working for the following reasons:

* Even though the cargo cache claims to have a cache hit, it doesn't seem to download crates' sources.  The fact that crates get redownloaded during the build phase attests to that.  Also, the amount of cached data for my first cached build was only 9MB, which is too small for this project (it should be at least 61MB).  Intriguingly, the amount of cached data increases by 9MB on every build.  I wonder if the cache is uploaded correctly, but downloaded to the wrong location?

* Even if the cache were working as advertised, it doesn't cache the `target/` directory.  Recompiling everything (including dependencies) takes more time than downloading dependencies.  Travis CI caches `target/` for that reason.  And Cirrus's docs on the subject (https://cirrus-ci.org/examples/#rust) don't show how to add a second directory to the cache.

Here's an example build that had a cache hit and yet had to redownload and build every dependency: https://cirrus-ci.com/task/6019171191619584 .

**Comment by Minoru** [comment]
@fkorotkov, that PR is merged now. What's next for this issue?

Apparently it's not fixed yet, because I've set up [a cache for ~/.cargo/registry](https://github.com/newsboat/newsboat/blob/686a53343f89a4e7702d2f0b4bd9f0bad7a3a914/.cirrus.yml#L13-L15), and [it gets restored all right](https://cirrus-ci.com/task/4679179908153344?command=cargo#L960) (although the upload stage says "//.cargo/registry", i.e. it expands `$HOME` to nothing). However, during the build all the crates get re-downloaded (can't provide the link to a line because it doesn't seem to work).

**Comment by fkorotkov** [comment]
@Minoru have you tried to set `HOME` as in https://github.com/bfffs/bfffs/pull/4? I don't think there anything we can do on Cirrus side it's just the way vanilla FreeBSD VM is configured without `HOME` but `cargo` seems relies on it.

**Comment by Minoru** [comment]
Yup, that did the trick. Thank you very much!

It'd be nice to have a note about this in the docs, though. Right now they only mention CARGO_HOME, and never even hint that the provided example might not work for some systems.
