### ISSUE TITLE
build_arguments not escaped on the command line

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#571]
When using Docker image as an environment, one can specify additional arguments like so:

```yaml
container:
  dockerfile: docker/ubuntu_18.04-build-tools.dockerfile
  docker_arguments:
      # We need llvm-symbolizer from llvm-9-tools to demangle symbols in
      # sanitizer's reports
      cxx_package: clang-9
      cc: clang-9
      cxx: clang++-9
```

Each argument turns into a `--build-arg` on the command line.

However, if the value in `docker_arguments` [contains a space](https://github.com/newsboat/newsboat/commit/5b63a83be0664a1413303348bddec891bcc1a397#diff-0f7067c31caedf7df2739c9b07efa122R224):

```yaml
      cxx_package: "clang-9 llvm-9"
```

...the value [gets interpreted by the shell as two separate arguments](https://cirrus-ci.com/task/6312890294599680?command=build#L0), because the space is not escaped in any way. That leads to Docker build failing.

To get around this, [I had to use double-backslash](https://github.com/newsboat/newsboat/commit/2d8af03435560bae5b51134bf733a4edafefba99#diff-0f7067c31caedf7df2739c9b07efa122R227):

```yaml
      cxx_package: "clang-9\\ llvm-9"
```

Cirrus's code un-escapes the value once, leaving a single backslash there, and [pastes that into the command line verbatim](https://cirrus-ci.com/task/5828875531845632?command=build#L0); the shell interprets `clang-9\ llvm-9` as a single argument, and the build proceeds fine.

It'd be nice if Cirrus hid those details from us, and quoted all arguments before putting them onto the command line.

**Comment by fkorotkov** [comment]
Oh! Indeed, it will be better to quote values of such arguments like `--build-arg cxx_package="clang-9 llvm-9"`. Just pushed a change to add it. Will close the issue once it's deployed. Thanks for finding it out and creating the issue! 🙌

**Comment by fkorotkov** [comment]
Forgot to close the issue, this is deployed and should be fixed now.

**Comment by Minoru** [comment]
Still doesn't work: [I removed the backslashes](https://github.com/newsboat/newsboat/commit/04d9757af4898ffb988ba3cfba4ea7aeacf8b8da), and [the build started failing again](https://cirrus-ci.com/task/5308041893511168?command=build#L0) with the same error. Do I need to wait for the deploy to propagate to all the workers or something?

**Comment by fkorotkov** [comment]
Indeed! Deployed failed. My apologies, just manually triggered a deploy and new builds should have proper quotation in the generated scripts.

**Comment by Minoru** [comment]
Sorry, still no luck: I clicked "Re-run" on the same job I linked above, and [it failed again](https://cirrus-ci.com/task/6312684282970112?command=build#L0). Perhaps I need to push a new commit or something?

**Comment by fkorotkov** [comment]
Yeah, re-run won't fix the issue since script of a new task will be the same (without quotes).

**Comment by Minoru** [comment]
Cool, a new commit fixed it. Thank you, @fkorotkov!
